jobs:
  provenance:
    needs:
    - release
    permissions:
      actions: read
      contents: write
      id-token: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: ${{ needs.release.outputs.hash }}
      provenance-name: ${{ needs.release.outputs.artifact_name }}.jar.intoto.jsonl
      upload-assets: true
  release:
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      TAG: ${{ github.ref_name }}
    outputs:
      artifact_name: ${{ steps.hash.outputs.artifact_name }}
      hash: ${{ steps.hash.outputs.hash }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Validate version name
      run: '[[ "$TAG" =~ jackson-core-[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)? ]] || exit
        1

        '
    - continue-on-error: true
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: '8'
        server-id: sonatype-nexus-staging
        server-password: CI_DEPLOY_PASSWORD
        server-username: CI_DEPLOY_USERNAME
    - continue-on-error: true
      env:
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      name: Perform release
      run: ./mvnw -B -q -ff -ntp release:perform -DlocalCheckout=true
    - continue-on-error: true
      id: hash
      name: Generate hash
      run: "ARTIFACT_NAME=\"$( \\\n  ./mvnw help:evaluate \\\n    -Dexpression=project.artifactId\
        \ -q -DforceStdout)-$( \\\n  ./mvnw help:evaluate \\\n    -Dexpression=project.version\
        \ -q -DforceStdout)\"\necho \"artifact_name=$ARTIFACT_NAME\" >> \"$GITHUB_OUTPUT\"\
        \n\ncd ./checkout/target\necho \"hash=$( \\\n  sha256sum $ARTIFACT_NAME*.jar\
        \ | \\\n  base64 -w0 \\\n)\" >> \"$GITHUB_OUTPUT\"\n\necho \"DEBUG: After\
        \ SLSA hash generation we have:\"\necho \"DEBUG: ARTIFACT_NAME = $ARTIFACT_NAME\"\
        \nls ./checkout\nls ./checkout/target\n"
name: Publish new release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
permissions:
  contents: read
