jobs:
  trigger-dep-build:
    name: Trigger downstream builds
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Repository dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        client-payload: '{"version": "N/A" }'
        event-type: jackson-core-pushed
        repository: ${{ matrix.repo }}
        token: ${{ secrets.token }}
    strategy:
      fail-fast: false
      matrix:
        repo:
        - FasterXML/jackson-databind
name: Trigger downstream builds
on:
  repository_dispatch:
    types: trigger-ga___trigger_dep_builds.yml
